### ISSUE TITLE
preprocessing 

### ISSUE THREAD

**Issue by congcongWY** [Astarakee/segrap2023#3]
Hello, can you request the task2 data preprocessing code, my email is wwy5150@163.com

**Comment by Astarakee** [comment]
Hi, the employed preprocessing steps are available at `./segrap2023/taskX/tools/` including
1) modality-based contrast enhancement:  
https://github.com/Astarakee/segrap2023/blob/ee2fe5885a8b3d3a224b24198f20fc1e93a8b2a0/task2/tools/prepare_data.py#L8
2) cropping full-resolution volume around the target region:
https://github.com/Astarakee/segrap2023/blob/ee2fe5885a8b3d3a224b24198f20fc1e93a8b2a0/task2/tools/cropping_stuff.py#L101
In general, the `main.py` shows the step by step functions from loader to preprocessing, cropping, segmentation and full-resolution reconstruction:
https://github.com/Astarakee/segrap2023/blob/ee2fe5885a8b3d3a224b24198f20fc1e93a8b2a0/task2/main.py#L18

**Comment by congcongWY** [comment]
thank you,can I ask again, when I run the cropping_stuff.py, it will report an error：
'TotalSegmentator' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'TotalSegmentator' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by congcongWY** [comment]
Hello, I am a novice in medical image processing, I am not very good at the data preprocessing, can I ask you about the dataset you have processed, please

**Comment by Astarakee** [comment]
Hi, I suggest you follow the README and, first, try to execute the inference pipeline via Docker.
